---

variables:
  OMP_NUM_THREADS: 1

stages:
  - setup
  - unit_test
  - system_test
  - deploy

.debian_gcc: &debian_gcc
  image: registry.dune-project.org/docker/ci/dune-pdelab:2.6
  tags:
    - "cores:2"

.debian_clang: &debian_clang
  image: registry.dune-project.org/docker/ci/dune-pdelab:2.6
  variables: {DUNECI_OPTS: /duneci/opts.clang}
  tags:
    - "cores:2"

.setup: &setup
  stage: setup
  script:
    - . /duneci/bin/duneci-init-job
    - duneci-install-module -r https://gitlab.dune-project.org/staging/dune-logging.git
  after_script:
    - mv /duneci/modules/dune-logging dune-logging
  artifacts:
    paths:
      - build-cmake/
      - dune-logging/

.unit_test: &unit_test
  stage: unit_test
  before_script:
    - . /duneci/bin/duneci-init-job
    - mv dune-logging /duneci/modules/dune-logging
  script: 
    - duneci-standard-test
    - ctest -L unit

.system_test: &system_test
  stage: system_test
  before_script:
    - . /duneci/bin/duneci-init-job
    - mv dune-logging /duneci/modules/dune-logging
  script: 
    - duneci-standard-test
    - ctest -L system

# gcc
setup:gcc:
  <<: *debian_gcc
  <<: *setup

unit_test:gcc:
  <<: *debian_gcc
  <<: *unit_test
  dependencies:
    - setup:gcc

system_test:gcc:
  <<: *debian_gcc
  <<: *system_test
  dependencies:
    - setup:gcc

# clang
setup:clang:
  <<: *debian_clang
  <<: *setup

unit_test:clang:
  <<: *debian_clang
  <<: *unit_test
  dependencies:
    - setup:clang

system_test:clang:
  <<: *debian_clang
  <<: *system_test
  dependencies:
    - setup:clang
