---

variables:
  GIT_CLONE_PATH: $CI_BUILDS_DIR/dune-copasi

stages:
  - setup
  # - build
  # - unit_test
  # - system_test
  # - deploy

# OS setup
.debian_gcc: &debian_gcc
  image: registry.dune-project.org/docker/ci/dune:2.6-debian-10-gcc-8-17
  tags:
    - "cores:2"

# .debian_clang: &debian_clang
#   image: debian:bionic
#   tags:
#     - "cores:2"

# Stages
.setup: &setup
  stage: setup
  script:
    - git clone -b releases/2.6 https://gitlab.dune-project.org/core/dune-common
    - git clone -r https://gitlab.dune-project.org/staging/dune-logging
    - git clone -b releases/2.6 https://gitlab.dune-project.org/core/dune-geometry
    - git clone -b releases/2.6 https://gitlab.dune-project.org/core/dune-grid
    - git clone -b releases/2.6 https://gitlab.dune-project.org/core/dune-istl
    - git clone -b releases/2.6 https://gitlab.dune-project.org/core/dune-localfunctions
    - git clone -b releases/2.6 https://gitlab.dune-project.org/staging/dune-functions
    - git clone -b releases/2.6 https://gitlab.dune-project.org/staging/dune-typetree
    - git clone -b releases/2.6 https://gitlab.dune-project.org/pdelab/dune-pdelab
    - git clone -b releases/2.6 https://gitlab.dune-project.org/extensions/dune-multidomaingrid
    
  artifacts:
    paths:
      - dune-*/

# .build: &build
#   stage: build
#   before_script:
#     - . /duneci/bin/duneci-init-job
#     - mv dune-logging /duneci/modules/dune-logging
#     - mv dune-multidomaingrid /duneci/modules/dune-multidomaingrid
#   after_script:
#     - mv /duneci/modules/dune-logging dune-logging
#     - mv /duneci/modules/dune-multidomaingrid dune-multidomaingrid
#   script:
#     - /duneci/modules/dune-common/bin/dunecontrol --opts=/duneci/dune.opts --only=dune-copasi vcsetup
#     - /duneci/modules/dune-common/bin/dunecontrol --opts=/duneci/dune.opts --only=dune-copasi configure
#     - /duneci/modules/dune-common/bin/dunecontrol --opts=/duneci/dune.opts --only=dune-copasi make -j2 all
#   artifacts:
#     paths:
#       - dune-logging/
#       - build-cmake/

# .unit_test: &unit_test
#   stage: unit_test
#   before_script:
#     - . /duneci/bin/duneci-init-job
#     - mv dune-logging /duneci/modules/dune-logging
#     - mv dune-multidomaingrid /duneci/modules/dune-multidomaingrid
#     - cd build-cmake
#   script: 
#     - make build_unit_tests
#     - ctest -j2 -L "unit" 

# .system_test: &system_test
#   stage: system_test
#   before_script:
#     - . /duneci/bin/duneci-init-job
#     - mv dune-logging /duneci/modules/dune-logging
#     - mv /duneci/modules/dune-multidomaingrid dune-multidomaingrid
#     - cd build-cmake
#   script: 
#     - make build_system_tests
#     - ctest -j2 -L "system"

# gcc
setup:gcc:
  <<: *debian_gcc
  <<: *setup

# build:gcc:
#   <<: *debian_gcc
#   <<: *build
#   dependencies:
#     - setup:gcc

# unit_test:gcc:
#   <<: *debian_gcc
#   <<: *unit_test
#   dependencies:
#     - build:gcc

# system_test:gcc:
#   <<: *debian_gcc
#   <<: *system_test
#   dependencies:
#     - build:gcc

# # clang
# setup:clang:
#   <<: *debian_clang
#   <<: *setup

# build:clang:
#   <<: *debian_clang
#   <<: *build
#   dependencies:
#     - setup:clang

# unit_test:clang:
#   <<: *debian_clang
#   <<: *unit_test
#   dependencies:
#     - build:clang

# system_test:clang:
#   <<: *debian_clang
#   <<: *system_test
#   dependencies:
#     - build:clang
