---

variables:
  OMP_NUM_THREADS: 1

stages:
  - setup
  - build
  - unit_test
  - system_test
  - deploy

# OS setup
.debian_gcc: &debian_gcc
  image: registry.dune-project.org/docker/ci/dune-pdelab:2.6
  tags:
    - "cores:2"

.debian_clang: &debian_clang
  image: registry.dune-project.org/docker/ci/dune-pdelab:2.6
  variables: {DUNECI_OPTS: /duneci/opts.clang}
  tags:
    - "cores:2"

# Stages
.setup: &setup
  stage: setup
  script:
    - . /duneci/bin/duneci-init-job
    - duneci-install-module -r https://gitlab.dune-project.org/staging/dune-logging.git
  after_script:
    - mv /duneci/modules/dune-logging dune-logging
  artifacts:
    paths:
      - dune-logging/

.build: &build
  stage: build
  before_script:
    - . /duneci/bin/duneci-init-job
    - mv dune-logging /duneci/modules/dune-logging
  after_script:
    - mv /duneci/modules/dune-logging dune-logging
  script:
    - /duneci/modules/dune-common/bin/dunecontrol --opts=/duneci/dune.opts --only=dune-copasi vcsetup
    - /duneci/modules/dune-common/bin/dunecontrol --opts=/duneci/dune.opts --only=dune-copasi configure
    - /duneci/modules/dune-common/bin/dunecontrol --opts=/duneci/dune.opts --only=dune-copasi make -j2 all
  artifacts:
    paths:
      - dune-logging/

.unit_test: &unit_test
  stage: unit_test
  before_script:
    - . /duneci/bin/duneci-init-job
    - mv dune-logging /duneci/modules/dune-logging
  script: 
    - ctest -j2 -L unit 

.system_test: &system_test
  stage: system_test
  before_script:
    - . /duneci/bin/duneci-init-job
    - mv dune-logging /duneci/modules/dune-logging
  script: 
    - ctest -j2 -L system

# gcc
setup:gcc:
  <<: *debian_gcc
  <<: *setup

build:gcc:
  <<: *debian_gcc
  <<: *build
  dependencies:
    - setup:gcc

unit_test:gcc:
  <<: *debian_gcc
  <<: *unit_test
  dependencies:
    - build:gcc

system_test:gcc:
  <<: *debian_gcc
  <<: *system_test
  dependencies:
    - build:gcc

# clang
setup:clang:
  <<: *debian_clang
  <<: *setup

build:clang:
  <<: *debian_clang
  <<: *build
  dependencies:
    - setup:clang

unit_test:clang:
  <<: *debian_clang
  <<: *unit_test
  dependencies:
    - build:clang

system_test:clang:
  <<: *debian_clang
  <<: *system_test
  dependencies:
    - build:clang
