---

stages:
  - setup
  # - build
  # - unit_test
  # - system_test
  # - deploy

.general_definitions: &general_definitions
  tags:
    - "cores:4"

# OS setup
.debian_gcc: &debian_gcc
  <<: *general_definitions
  image: registry.dune-project.org/docker/ci/debian:10
  variables:
    CI_BUILDS_DIR: /builds/copasi/dune-copasi
    DUNECI_TOOLCHAIN: "gcc-8-17"

.debian_clang: &debian_clang
  <<: *general_definitions
  image: registry.dune-project.org/docker/ci/debian:10
  variables:
    CI_BUILDS_DIR: /builds/copasi/dune-copasi
    DUNECI_TOOLCHAIN: "clang-7-libcpp-17"
  allow_failure: true

.ubuntu_gcc: &ubuntu_gcc
  <<: *general_definitions
  image:  registry.dune-project.org/docker/ci/ubuntu:18.04
  variables:
    CI_BUILDS_DIR: /builds/copasi/dune-copasi
    DUNECI_TOOLCHAIN: "gcc-7-17"

.ubuntu_clang: &ubuntu_clang
  <<: *general_definitions
  image: registry.dune-project.org/docker/ci/ubuntu:18.04
  variables:
    CI_BUILDS_DIR: /builds/copasi/dune-copasi
    DUNECI_TOOLCHAIN: "clang-6-17"

# Stages
.setup: &setup
  stage: setup
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t registry.dune-project.org/copasi/dune-copasi/requirements -f docker/requirements.dockerfile .
  tags:
    - "dind"
    
# .build: &build
#   stage: build
#   script:
#     - $DUNECONTROL --opts=/duneci/dune.opts --only=dune-copasi all

# .unit_test: &unit_test
#   stage: unit_test
#   script: 
#     - echo 'CMAKE_FLAGS+=" -DCMAKE_BUILD_TYPE=Debug"' >> /duneci/cmake-flags/dune_copasi.opts
#     - $DUNECONTROL --opts=/duneci/dune.opts --only=dune-copasi configure
#     - $DUNECONTROL --opts=/duneci/dune.opts --only=dune-copasi make --target build_unit_tests
#     - $DUNECONTROL --opts=/duneci/dune.opts --only=dune-copasi bexec ctest -j4 -L "unit"
#   artifacts:
#     paths:
#       - build/dune-copasi/test
#     expire_in: 1 day

# .system_test: &system_test
#   stage: system_test
#   script: 
#     - $DUNECONTROL --opts=/duneci/dune.opts --only=dune-copasi bexec ctest -j4 -L "DUNE_SYSTEMTEST"
#   artifacts:
#     paths:
#       - build/dune-copasi/test
#     expire_in: 1 day

# debian gcc
setup:debian_gcc:
  <<: *debian_gcc
  <<: *setup

# build:debian_gcc:
#   <<: *debian_gcc
#   <<: *build
#   dependencies:
#     - setup:debian_gcc

# unit_test:debian_gcc:
#   <<: *debian_gcc
#   <<: *unit_test
#   dependencies:
#     - build:debian_gcc

# system_test:debian_gcc:
#   <<: *debian_gcc
#   <<: *system_test
#   dependencies:
#     - build:debian_gcc

# # ubuntu gcc
# setup:ubuntu_gcc:
#   <<: *ubuntu_gcc
#   <<: *setup  

# build:ubuntu_gcc:
#   <<: *ubuntu_gcc
#   <<: *build
#   dependencies:
#     - setup:ubuntu_gcc

# unit_test:ubuntu_gcc:
#   <<: *ubuntu_gcc
#   <<: *unit_test
#   dependencies:
#     - build:ubuntu_gcc

# system_test:ubuntu_gcc:
#   <<: *ubuntu_gcc
#   <<: *system_test
#   dependencies:
#     - build:ubuntu_gcc

# # debian clang
# setup:debian_clang:
#   <<: *debian_clang
#   <<: *setup

# build:debian_clang:
#   <<: *debian_clang
#   <<: *build
#   dependencies:
#     - setup:debian_clang

# unit_test:debian_clang:
#   <<: *debian_clang
#   <<: *unit_test
#   dependencies:
#     - build:debian_clang

# system_test:debian_clang:
#   <<: *debian_clang
#   <<: *system_test
#   dependencies:
#     - build:debian_clang

# # ubuntu clang
# setup:ubuntu_clang:
#   <<: *ubuntu_clang
#   <<: *setup  

# build:ubuntu_clang:
#   <<: *ubuntu_clang
#   <<: *build
#   dependencies:
#     - setup:ubuntu_clang

# unit_test:ubuntu_clang:
#   <<: *ubuntu_clang
#   <<: *unit_test
#   dependencies:
#     - build:ubuntu_clang

# system_test:ubuntu_clang:
#   <<: *ubuntu_clang
#   <<: *system_test
#   dependencies:
#     - build:ubuntu_clang    