image: gcc

stages:
  - configure
  - build

configure:
  stage: configure
  script:
    - cd ..
    - git clone -b releases/2.6 https://gitlab.dune-project.org/core/dune-common
    - git clone -b releases/2.6 https://gitlab.dune-project.org/core/dune-geometry
    - git clone -b releases/2.6 https://gitlab.dune-project.org/core/dune-grid
    - git clone -b releases/2.6 https://gitlab.dune-project.org/core/dune-istl
    - git clone -b releases/2.6 https://gitlab.dune-project.org/core/dune-localfunctions
    - git clone -b releases/2.6 https://gitlab.dune-project.org/staging/dune-functions
    - git clone -b releases/2.6 https://gitlab.dune-project.org/staging/dune-typetree
    - git clone -b releases/2.6 https://gitlab.dune-project.org/pdelab/dune-pdelab
    - ./dune-common/bin/dunecontrol --builddir=$PWD/build-clang-debug --module=dune-pdelab all

build:
  stage: build
  script:
    - ./dune-common/bin/dunecontrol --builddir=$PWD/build-clang-debug --only=dune-copasi all