---

variables:
  OMP_NUM_THREADS: 1

before_script:
  - ./duneci/bin/duneci-init-job
  - duneci-install-module https://gitlab.dune-project.org/staging/dune-logging.git

debian:10--gcc:
  image: registry.dune-project.org/docker/ci/dune-pdelab:2.6
  script: 
    - duneci-standard-test
    - ctest -L system
  tags:
    - "cores:2"

debian:10--clang:
  image: registry.dune-project.org/docker/ci/dune-pdelab:2.6
  script: 
    - duneci-standard-test
    - ctest -L system
  variables: {DUNECI_OPTS: /duneci/opts.clang}
  tags:
    - "cores:2"